add ability to make pull requests

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -144,12 +144,18 @@ parse_args() {
 	FLAGS "$@" || exit $?
 	eval set -- "${FLAGS_ARGV}"
 
-	# Read arguments into global variables
-	if [ -z $1 ]; then
-		VERSION=''
-	else
-		VERSION=$1
+  VERSION=''
+  PR_FUNC=''
+  # read arguments into global variables
+  if type $1 2>/dev/null | grep -q 'function'; then
+    if [[ -n $2 ]]; then
+      PR_FUNC=$1
+		  VERSION=$2
+    else PR_FUNC=$1
+    fi
+	elif [[ -n $1 ]]; then VERSION=$1;
 	fi
+
 	BRANCH=$PREFIX$VERSION
 }
 
@@ -361,7 +367,7 @@ showcommands!     Show git commands while executing them
 
 cmd_finish() {
 	OPTIONS_SPEC="\
-git flow hotfix finish [-h] [-F] [-s] [-u] [-m | -f ] [-p] [-k] [-n] [-b] [-S] <version>
+git flow hotfix finish [-h] [-F] [-s] [-u] [-m | -f ] [-p] [-P] [-k] [-n] [-b] [-S] <version>
 
 Finish hotfix branch <version>
 --
@@ -373,6 +379,7 @@ u,[no]signingkey      Use the given GPG-key for the digital signature (implies -
 m,[no]message         Use the given tag message
 f,[no]messagefile=    Use the contents of the given file as tag message
 p,[no]push            Push to origin after performing finish
+P,[no]pull-request    Create a pull request
 k,[no]keep            Keep branch after performing finish
 [no]keepremote        Keep the remote branch
 [no]keeplocal         Keep the local branch
@@ -391,6 +398,7 @@ T,tagname!            Use given tag name
 	DEFINE_string  'message' "" "use the given tag message" m
 	DEFINE_string  'messagefile' "" "use the contents of the given file as tag message" f
 	DEFINE_boolean 'push' false "push to $ORIGIN after performing finish" p
+  DEFINE_boolean 'pull-request' false 'create a pull request instead of merging locally' P
 	DEFINE_boolean 'keep' false "keep branch after performing finish" k
 	DEFINE_boolean 'keepremote' false "keep the remote branch"
 	DEFINE_boolean 'keeplocal' false "keep the local branch"
@@ -516,7 +524,9 @@ T,tagname!            Use given tag name
 	# Try to merge into BASE.
 	# In case a previous attempt to finish this release branch has failed,
 	# but the merge into BASE was successful, we skip it now
-	if ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
+  if flag pull_request && [[ -n $PR_FUNC ]]; then
+    $PR_FUNC $BRANCH $BASE_BRANCH
+	elif ! git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
 		git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 		if noflag squash; then
 			git_do merge --no-ff "$BRANCH" || die "There were merge conflicts." # TODO: What do we do now?
@@ -548,37 +558,38 @@ T,tagname!            Use given tag name
 		fi
 	fi
 
-	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-		# By default we back-merge the $MASTER_BRANCH unless the user explicitly
-		# stated not to do a back-merge, in that case we use the $BRANCH.
-		if noflag nobackmerge; then
-			MERGE_BRANCH="$BASE_BRANCH"
-		else
-			MERGE_BRANCH="$BRANCH"
-		fi
+  # Commented to prevent back merging
+	# if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+	# 	# By default we back-merge the $MASTER_BRANCH unless the user explicitly
+	# 	# stated not to do a back-merge, in that case we use the $BRANCH.
+	# 	if noflag nobackmerge; then
+	# 		MERGE_BRANCH="$BASE_BRANCH"
+	# 	else
+	# 		MERGE_BRANCH="$BRANCH"
+	# 	fi
 
-		# Try to merge into develop.
-		# In case a previous attempt to finish this release branch has failed,
-		# but the merge into develop was successful, we skip it now
-		if ! git_is_branch_merged_into "$MERGE_BRANCH" "$DEVELOP_BRANCH"; then
-			git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+	# 	# Try to merge into develop.
+	# 	# In case a previous attempt to finish this release branch has failed,
+	# 	# but the merge into develop was successful, we skip it now
+	# 	if ! git_is_branch_merged_into "$MERGE_BRANCH" "$DEVELOP_BRANCH"; then
+	# 		git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
 
-			if noflag nobackmerge; then
-				# Accounting for 'git describe', if a release is tagged
-				# we use the tag commit instead of the branch.
-				if noflag notag; then
-					commit="$VERSION_PREFIX$TAGNAME"
-				else
-					commit="$BASE_BRANCH"
-				fi
-			else
-				commit="$BRANCH"
-			fi
+	# 		if noflag nobackmerge; then
+	# 			# Accounting for 'git describe', if a release is tagged
+	# 			# we use the tag commit instead of the branch.
+	# 			if noflag notag; then
+	# 				commit="$VERSION_PREFIX$TAGNAME"
+	# 			else
+	# 				commit="$BASE_BRANCH"
+	# 			fi
+	# 		else
+	# 			commit="$BRANCH"
+	# 		fi
 
-			git_do merge --no-ff "$commit" || die "There were merge conflicts."
-			# TODO: What do we do now?
-		fi
-	fi
+	# 		git_do merge --no-ff "$commit" || die "There were merge conflicts."
+	# 		# TODO: What do we do now?
+	# 	fi
+	# fi
 
 	run_post_hook "$VERSION_PREFIX$TAGNAME" "$ORIGIN" "$BRANCH"
 
