set force deletion to have precedence over merge status
force deletion was failing when a branch was deleted but couldn't be
verified as having been merged properly. Setting force check as
the first check fixes this

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -813,17 +813,17 @@ r,[no]remote     Delete remote branch
 		fi
 	fi
 
-	if git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
-		git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
-		if flag remote; then
-			git_remote_branch_delete "$BRANCH"
-		fi
+  if flag force; then
+	  git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
+	  if flag remote; then
+	  	git_remote_branch_delete "$BRANCH"
+	  fi
 	else
-		if flag force; then
-			git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
-			if flag remote; then
-				git_remote_branch_delete "$BRANCH"
-			fi
+		if git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH"; then
+		  git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+		  if flag remote; then
+		  	git_remote_branch_delete "$BRANCH"
+		  fi
 		else
 			die "Feature branch '$BRANCH' has been not been merged yet. Use -f to force the deletion."
 		fi
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -1079,17 +1079,17 @@ r,[no]remote     Delete remote branch
 		fi
 	fi
 
-	if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH" ); then
-		git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+  if flag force; then
+		git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
 		if flag remote; then
 			git_remote_branch_delete "$BRANCH"
 		fi
 	else
-		if flag force; then
-			git_do branch -D "$BRANCH" || die "Could not delete the $BRANCH."
-			if flag remote; then
-				git_remote_branch_delete "$BRANCH"
-			fi
+	  if ( git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH" && git_is_branch_merged_into "$BRANCH" "$BASE_BRANCH" ); then
+		  git_do branch -d "$BRANCH" || die "Could not delete the $BRANCH."
+		  if flag remote; then
+		  	git_remote_branch_delete "$BRANCH"
+		  fi
 		else
 			die "Release branch '$BRANCH' has been not been merged in branch '$MASTER_BRANCH' and/or branch '$BASE_BRANCH'. Use -f to force the deletion."
 		fi
