commentd out lines preventing merge request workflow

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -231,18 +231,18 @@ F,[no]fetch       Fetch from origin before performing local operation
 
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH" "$base"
 
-	echo
-	echo "Summary of actions:"
-	echo "- A new branch '$BRANCH' was created, based on '$base'"
-	echo "- You are now on branch '$(git_current_branch)'"
-	echo
-	echo "Follow-up actions:"
-	echo "- Start committing your hot fixes"
-	echo "- Bump the version number now!"
-	echo "- When done, run:"
-	echo
-	echo "     git flow hotfix finish '$VERSION'"
-	echo
+	# echo
+	# echo "Summary of actions:"
+	# echo "- A new branch '$BRANCH' was created, based on '$base'"
+	# echo "- You are now on branch '$(git_current_branch)'"
+	# echo
+	# echo "Follow-up actions:"
+	# echo "- Start committing your hot fixes"
+	# echo "- Bump the version number now!"
+	# echo "- When done, run:"
+	# echo
+	# echo "     git flow hotfix finish '$VERSION'"
+	# echo
 }
 
 cmd_publish() {
@@ -591,88 +591,88 @@ T,tagname!            Use given tag name
 	# 	fi
 	# fi
 
-	run_post_hook "$VERSION_PREFIX$TAGNAME" "$ORIGIN" "$BRANCH"
+	# run_post_hook "$VERSION_PREFIX$TAGNAME" "$ORIGIN" "$BRANCH"
 
 	# Delete branch
-	if noflag keep; then
+	# if noflag keep; then
 
-		# Always delete remote first
-		if noflag keepremote;then
-			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
-			fi
-		fi
+	# 	# Always delete remote first
+	# 	if noflag keepremote;then
+	# 		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+	# 			git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
+	# 		fi
+	# 	fi
 
-		# Delete local after remote to avoid warnings
-		if noflag keeplocal; then
-			if [ "$BRANCH" = "$(git_current_branch)" ]; then
-				git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
-			fi
-			if flag force_delete; then
-				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-			else
-				git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-			fi
-		fi
+	# 	# Delete local after remote to avoid warnings
+	# 	if noflag keeplocal; then
+	# 		if [ "$BRANCH" = "$(git_current_branch)" ]; then
+	# 			git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+	# 		fi
+	# 		if flag force_delete; then
+	# 			git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+	# 		else
+	# 			git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+	# 		fi
+	# 	fi
 
-		# no more branches: we can safely remove config section
-		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
-			gitflow_config_remove_base_section "$BRANCH"
-		fi
+	# 	# no more branches: we can safely remove config section
+	# 	if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
+	# 		gitflow_config_remove_base_section "$BRANCH"
+	# 	fi
 
-	fi
+	# fi
 
-	if flag push; then
-		if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-			git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
-		fi
-		git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
-		if noflag notag; then
-			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
-		fi
-	fi
+	# if flag push; then
+	# 	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+	# 		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+	# 	fi
+	# 	git_do push "$ORIGIN" "$BASE_BRANCH" || die "Could not push branch '$BASE_BRANCH' to remote '$ORIGIN'."
+	# 	if noflag notag; then
+	# 		git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+	# 	fi
+	# fi
 
-	echo
-	echo "Summary of actions:"
-	if flag fetch; then
-		echo "- Latest objects have been fetched from '$ORIGIN'"
-	fi
-	echo "- Hotfix branch '$BRANCH' has been merged into '$BASE_BRANCH'"
-	if noflag notag; then
-		echo "- The hotfix was tagged '$VERSION_PREFIX$TAGNAME'"
-	fi
-	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-		[ "$commit" = "$BASE_BRANCH" ] && echo "- Master branch '$BASE_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
-		[ "$commit" = "$VERSION_PREFIX$TAGNAME" ] && echo "- Hotfix tag '$VERSION_PREFIX$TAGNAME' has been back-merged into '$DEVELOP_BRANCH'"
-		[ "$commit" = "$BRANCH" ] && echo "- Hotfix branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
-	fi
-	if noflag keep; then
-		if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
-			keepmsg="has been locally deleted"
-		else
-			keepmsg="is still locally available"
-		fi
-		if [ $remotebranchdeleted -eq $FLAGS_TRUE ]; then
-			keepmsg=$keepmsg"; it has been remotely deleted from '$ORIGIN'"
-		elif git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
-		fi
-	else
-		keepmsg="is still locally available"
-		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
-		fi
-	fi
-	echo "- Hotfix branch '$BRANCH' "$keepmsg
-	if flag push; then
-		if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
-			echo "- '$DEVELOP_BRANCH', '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
-		else
-			echo "- '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
-		fi
-	fi
-	echo "- You are now on branch '$(git_current_branch)'"
-	echo
+	# echo
+	# echo "Summary of actions:"
+	# if flag fetch; then
+	# 	echo "- Latest objects have been fetched from '$ORIGIN'"
+	# fi
+	# echo "- Hotfix branch '$BRANCH' has been merged into '$BASE_BRANCH'"
+	# if noflag notag; then
+	# 	echo "- The hotfix was tagged '$VERSION_PREFIX$TAGNAME'"
+	# fi
+	# if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+	# 	[ "$commit" = "$BASE_BRANCH" ] && echo "- Master branch '$BASE_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
+	# 	[ "$commit" = "$VERSION_PREFIX$TAGNAME" ] && echo "- Hotfix tag '$VERSION_PREFIX$TAGNAME' has been back-merged into '$DEVELOP_BRANCH'"
+	# 	[ "$commit" = "$BRANCH" ] && echo "- Hotfix branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
+	# fi
+	# if noflag keep; then
+	# 	if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
+	# 		keepmsg="has been locally deleted"
+	# 	else
+	# 		keepmsg="is still locally available"
+	# 	fi
+	# 	if [ $remotebranchdeleted -eq $FLAGS_TRUE ]; then
+	# 		keepmsg=$keepmsg"; it has been remotely deleted from '$ORIGIN'"
+	# 	elif git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+	# 		keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
+	# 	fi
+	# else
+	# 	keepmsg="is still locally available"
+	# 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+	# 		keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
+	# 	fi
+	# fi
+	# echo "- Hotfix branch '$BRANCH' "$keepmsg
+	# if flag push; then
+	# 	if [ "$BASE_BRANCH" = "$MASTER_BRANCH" ]; then
+	# 		echo "- '$DEVELOP_BRANCH', '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
+	# 	else
+	# 		echo "- '$BASE_BRANCH' and tags have been pushed to '$ORIGIN'"
+	# 	fi
+	# fi
+	# echo "- You are now on branch '$(git_current_branch)'"
+	# echo
 
 }
 
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -139,125 +139,125 @@ _finish_from_develop() {
 
 	# By default we backmerge the $MASTER_BRANCH unless the user explicitly
 	# stated not to do a back merge, in that case we use the $BRANCH.
-	if noflag nobackmerge; then
-		merge_branch="$MASTER_BRANCH"
-	else
-		merge_branch="$BRANCH"
-	fi
+	# if noflag nobackmerge; then
+	# 	merge_branch="$MASTER_BRANCH"
+	# else
+	# 	merge_branch="$BRANCH"
+	# fi
 
-	# Try to merge into develop unless 'nodevelopmerge' has been specified.
-	# In case a previous attempt to finish this release branch has failed,
-	# but the merge into develop was successful, we skip it now
-	if noflag nodevelopmerge; then
-		if ! git_is_branch_merged_into "$merge_branch" "$DEVELOP_BRANCH"; then
-			git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
+	# # Try to merge into develop unless 'nodevelopmerge' has been specified.
+	# # In case a previous attempt to finish this release branch has failed,
+	# # but the merge into develop was successful, we skip it now
+	# if noflag nodevelopmerge; then
+	# 	if ! git_is_branch_merged_into "$merge_branch" "$DEVELOP_BRANCH"; then
+	# 		git_do checkout "$DEVELOP_BRANCH" || die "Could not check out branch '$DEVELOP_BRANCH'."
 
-			if noflag nobackmerge; then
-				# Accounting for 'git describe', if a release is tagged
-				# we use the tag commit instead of the branch.
-				if noflag notag; then
-					commit="$VERSION_PREFIX$TAGNAME"
-				else
-					commit="$MASTER_BRANCH"
-				fi
-				git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-			else
-				commit="$BRANCH"
-				if noflag squash; then
-					git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-				else
-					git_do merge --squash "$commit" || die "There were merge conflicts." # TODO: What do we do now?
-					flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$DEVELOP_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
-					git_do commit
-				fi
-			fi
-		fi
-	fi
+	# 		if noflag nobackmerge; then
+	# 			# Accounting for 'git describe', if a release is tagged
+	# 			# we use the tag commit instead of the branch.
+	# 			if noflag notag; then
+	# 				commit="$VERSION_PREFIX$TAGNAME"
+	# 			else
+	# 				commit="$MASTER_BRANCH"
+	# 			fi
+	# 			git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+	# 		else
+	# 			commit="$BRANCH"
+	# 			if noflag squash; then
+	# 				git_do merge --no-ff "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+	# 			else
+	# 				git_do merge --squash "$commit" || die "There were merge conflicts." # TODO: What do we do now?
+	# 				flag squash_info && gitflow_create_squash_message "Merged release branch '$BRANCH'" "$DEVELOP_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
+	# 				git_do commit
+	# 			fi
+	# 		fi
+	# 	fi
+	# fi
 
-	run_post_hook "$VERSION_PREFIX$TAGNAME" "$ORIGIN" "$BRANCH"
+	# run_post_hook "$VERSION_PREFIX$TAGNAME" "$ORIGIN" "$BRANCH"
 
-	# Delete branch
-	if noflag keep; then
+	# # Delete branch
+	# if noflag keep; then
 
-		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-			git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
-		fi
+	# 	if [ "$BRANCH" = "$(git_current_branch)" ]; then
+	# 		git_do checkout "$MASTER_BRANCH" || die "Could not check out branch '$MASTER_BRANCH'."
+	# 	fi
 
-		# Always delete remote first
-		if noflag keepremote;then
-			if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-				git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
-			fi
-		fi
+	# 	# Always delete remote first
+	# 	if noflag keepremote;then
+	# 		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+	# 			git_remote_branch_delete "$BRANCH" && remotebranchdeleted=$FLAGS_TRUE
+	# 		fi
+	# 	fi
 
-		# Delete local after remote to avoid warnings
-		if noflag keeplocal; then
-			if flag force_delete; then
-				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-			else
-				if noflag squash; then
-					git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-				else
-					git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
-				fi
-			fi
-		fi
+	# 	# Delete local after remote to avoid warnings
+	# 	if noflag keeplocal; then
+	# 		if flag force_delete; then
+	# 			git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+	# 		else
+	# 			if noflag squash; then
+	# 				git_do branch -d "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+	# 			else
+	# 				git_do branch -D "$BRANCH" && localbranchdeleted=$FLAGS_TRUE
+	# 			fi
+	# 		fi
+	# 	fi
 
 		# no more branches: we can safely remove config section
 		if ! git_remote_branch_exists "$ORIGIN/$BRANCH" -a ! git_local_branch_exists "$BRANCH"; then
 			gitflow_config_remove_base_section "$BRANCH"
 		fi
-	fi
+	# fi
 
-	if flag push; then
-		if flag pushdevelop; then
-			git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
-		fi
-		if flag pushproduction; then
-			git_do push "$ORIGIN" "$MASTER_BRANCH" || die "Could not push branch '$MASTER_BRANCH' to remote '$ORIGIN'."
-		fi
-		if noflag notag && flag pushtag; then
-			git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
-		fi
-	fi
+	# if flag push; then
+	# 	if flag pushdevelop; then
+	# 		git_do push "$ORIGIN" "$DEVELOP_BRANCH" || die "Could not push branch '$DEVELOP_BRANCH' to remote '$ORIGIN'."
+	# 	fi
+	# 	if flag pushproduction; then
+	# 		git_do push "$ORIGIN" "$MASTER_BRANCH" || die "Could not push branch '$MASTER_BRANCH' to remote '$ORIGIN'."
+	# 	fi
+	# 	if noflag notag && flag pushtag; then
+	# 		git_do push --tags "$ORIGIN" || die "Could not push tags to remote '$ORIGIN'."
+	# 	fi
+	# fi
 
-	echo
-	echo "Summary of actions:"
-	if flag fetch; then
-		echo "- Latest objects have been fetched from '$ORIGIN'"
-	fi
-	echo "- Release branch '$BRANCH' has been merged into '$MASTER_BRANCH'"
-	if noflag notag; then
-		echo "- The release was tagged '$VERSION_PREFIX$TAGNAME'"
-	fi
-	[ "$commit" = "$MASTER_BRANCH" ] && echo "- Master branch '$MASTER_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
-	[ "$commit" = "$VERSION_PREFIX$TAGNAME" ] && echo "- Release tag '$VERSION_PREFIX$TAGNAME' has been back-merged into '$DEVELOP_BRANCH'"
-	[ "$commit" = "$BRANCH" ] && echo "- Release branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
+	# echo
+	# echo "Summary of actions:"
+	# if flag fetch; then
+	# 	echo "- Latest objects have been fetched from '$ORIGIN'"
+	# fi
+	# echo "- Release branch '$BRANCH' has been merged into '$MASTER_BRANCH'"
+	# if noflag notag; then
+	# 	echo "- The release was tagged '$VERSION_PREFIX$TAGNAME'"
+	# fi
+	# [ "$commit" = "$MASTER_BRANCH" ] && echo "- Master branch '$MASTER_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
+	# [ "$commit" = "$VERSION_PREFIX$TAGNAME" ] && echo "- Release tag '$VERSION_PREFIX$TAGNAME' has been back-merged into '$DEVELOP_BRANCH'"
+	# [ "$commit" = "$BRANCH" ] && echo "- Release branch '$BRANCH' has been merged into '$DEVELOP_BRANCH'"
 
-	if noflag keep; then
-		if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
-			keepmsg="has been locally deleted"
-		else
-			keepmsg="is still locally available"
-		fi
-		if [ $remotebranchdeleted -eq $FLAGS_TRUE ]; then
-			keepmsg=$keepmsg"; it has been remotely deleted from '$ORIGIN'"
-		elif git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
-		fi
-	else
-		keepmsg="is still locally available"
-		if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-			keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
-		fi
-	fi
-	echo "- Release branch '$BRANCH' "$keepmsg
+	# if noflag keep; then
+	# 	if [ $localbranchdeleted -eq $FLAGS_TRUE ]; then
+	# 		keepmsg="has been locally deleted"
+	# 	else
+	# 		keepmsg="is still locally available"
+	# 	fi
+	# 	if [ $remotebranchdeleted -eq $FLAGS_TRUE ]; then
+	# 		keepmsg=$keepmsg"; it has been remotely deleted from '$ORIGIN'"
+	# 	elif git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+	# 		keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
+	# 	fi
+	# else
+	# 	keepmsg="is still locally available"
+	# 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
+	# 		keepmsg=$keepmsg"; it is still remotely available on '$ORIGIN'"
+	# 	fi
+	# fi
+	# echo "- Release branch '$BRANCH' "$keepmsg
 
-	if flag push; then
-		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
-	fi
-	echo "- You are now on branch '$(git_current_branch)'"
-	echo
+	# if flag push; then
+	# 	echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+	# fi
+	# echo "- You are now on branch '$(git_current_branch)'"
+	# echo
 }
 
 #
@@ -595,18 +595,18 @@ v,verbose!           Verbose (more) output
 
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH" "$base"
 
-	echo
-	echo "Summary of actions:"
-	echo "- A new branch '$BRANCH' was created, based on '$base'"
-	echo "- You are now on branch '$(git_current_branch)'"
-	echo
-	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
-	echo "- Start committing last-minute fixes in preparing your release"
-	echo "- When done, run:"
-	echo
-	echo "     git flow release finish '$VERSION'"
-	echo
+	# echo
+	# echo "Summary of actions:"
+	# echo "- A new branch '$BRANCH' was created, based on '$base'"
+	# echo "- You are now on branch '$(git_current_branch)'"
+	# echo
+	# echo "Follow-up actions:"
+	# echo "- Bump the version number now!"
+	# echo "- Start committing last-minute fixes in preparing your release"
+	# echo "- When done, run:"
+	# echo
+	# echo "     git flow release finish '$VERSION'"
+	# echo
 }
 
 cmd_finish() {
